### ISSUE TITLE
Cordova Build Failure on Starter Template

### ISSUE THREAD

**Issue by triz231** [EddyVerbruggen/Calendar-PhoneGap-Plugin#170]
Per the CLI Automatic Installation instructions I completed the following steps on a brand new starter template:
(1) $ cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git
- NOTE:  This worked
(2) and run this command afterwards:  $ cordova build
- NOTE:  I received the below failure:
** BUILD FAILED **

The following build commands failed:
	CompileC build/myApp.build/Debug-iphonesimulator/myApp.build/Objects-normal/i386/Calendar.o myApp/Plugins/nl.x-services.plugins.calendar/Calendar.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /Users/stellar/desktop/myApp/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

Any guidance on how to proceed would be helpful.  

Best Regards,

Troy McKnight

**Comment by EddyVerbruggen** [comment]
Hi Troy,

I just did these steps and had no issues. Can you see what's different here?

I have OSX Yosemite /w XCode 6.3.

```
cordova -v  --> 5.0.0
cordova create calendartest
cd calendartest
cordova platform add ios
cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git
cordova build
```

**Comment by triz231** [comment]
Eddy,

Well, the only thing that is different is that my version of cordova is 4.1.2.  I ran exactly as you did and the Build Succeeded.  Not sure why it was different before when I first created the Ionic starter project and then tried to add your .git, and run the build.  Once the build succeeded, I ran an ionic serve to “see” if the calendar would be viewable.  I currently have the Apache Cordova icon saying it is Connecting to Device.  Is this what it is supposed to do?  

For the past two weeks I have been trying to do what you just did in 5 minutes.  Thank you.  Since you are the master of this plug-in, let me ask you a question… what I am ultimately trying to figure out is either (a) can I put a monthly calendar with the functionality (I think) your plug-in allows on its own slider with a custom background image, or (b) by using the plug-in by itself, can I introduce custom background images for each month.  

Do you have any thoughts?


Best Regards, 

Troy

**Comment by triz231** [comment]
Eddy,

I successfully ran the below build, and I emulated it in the browser and iOS emulator.  In both cases, it sits not he home screen with the Apache icon and a “Device is Ready” message.  I imagine this is correct since it is not connected to any device calendar?  What do I need to do to “see” a calendar as I test it?

Best Regards,

Troy

**Comment by triz231** [comment]
Eddy,

Now that I have a successful cordova build using your code, can you lend insight into what the best way to see a calendar in the project would be?  I understand (conceptually) why no calendar is viewable in the browser test and the iOS emulator - but I do not know what to do next to try and customize the output/imaging.  

Best Regards, 

Troy
