### ISSUE TITLE
Cordova build error, exit code 65

### ISSUE THREAD

**Issue by datomnurdin** [EddyVerbruggen/Calendar-PhoneGap-Plugin#172]
I created a new starter app (myApp), and ran the following instructions from the documentation:
```
$ cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git
```
and run this command afterwards:
```
$ cordova build
```
From there I get the following Failure:

```
** BUILD FAILED **
```

The following build commands failed:

```
CompileC build/myApp.build/Debug-iphonesimulator/myApp.build/Object-normal/i386/Calendar.o myApp/Plugins/nl.x-services.plugins.calendar/Calendar.m normal i386 objective-c  com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /Users/stellar/desktop/myApp/platforms/ios/cordova/build: Command failed with exit code 65
at ChildProcess.whenDone    (/usr/local/lib/node_modules/cordova/node_modules/cordova- lib/src/cordova/superspawn.js:135:23)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```
Any guidance on how to proceed?

**Comment by EddyVerbruggen** [comment]
Hi, started app: Ionic or Cordova CLI? I tested this yesterday with a new Cordova CLI project without problems so I'm very keep on finding out what the rootcause is.

**Comment by datomnurdin** [comment]
Noted.
