### ISSUE TITLE
App crashes if Calendar App is uninstalled on Android device

### ISSUE THREAD

**Issue by fahadhabib** [EddyVerbruggen/Calendar-PhoneGap-Plugin#266]
Hi,

App crashes if Calendar App is uninstalled on an Android device when trying to findEvents(). We are getting NullPointerException in AbstractCalendarAccessor class at line 241. It should return to ErrorCallback such that it can be handled by calling JS. 

We are using version 4.4.6 of plugin. This was working fine in previous version of plugin we used (v4.3.0)

Is there a way to check existence of Calendar or Calendar App on device?

Thanks

Fahad

**Comment by EddyVerbruggen** [comment]
Hi, sound like a sensible thing to do - would you mind sending a PR for that change?

**Comment by fahadhabib** [comment]
Hi Eddy,

That's quick response. I am not sure if I understand your response correctly. Do you want me to initiate a Pull Request for this change?

Here is the LogCat log for the error (if helps):

E/ActivityThread: Failed to find provider info for com.android.calendar
W/dalvikvm: threadid=12: thread exiting with uncaught exception (group=0x41598300)
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
				 java.lang.NullPointerException
					 at nl.xservices.plugins.accessor.AbstractCalendarAccessor.fetchEventInstances(AbstractCalendarAccessor.java:215)
					 at nl.xservices.plugins.accessor.AbstractCalendarAccessor.findEvents(AbstractCalendarAccessor.java:389)
					 at nl.xservices.plugins.Calendar$7.run(Calendar.java:393)
					 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
					 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
					 at java.lang.Thread.run(Thread.java:856)

Thanks

Fahad

**Comment by EddyVerbruggen** [comment]
If you can, yes. That would be the quickest way to tackle this If you have time of course ;)

**Comment by fahadhabib** [comment]
Let me see if I can do that. Never used GitHub to do it before, so might take some time...

Fahad

**Comment by aperezcoinpre** [comment]
Hi @fahadhabib , did you resolve the problem?
