### ISSUE TITLE
build.phonegap.com - Android BUILD FAILED

### ISSUE THREAD

**Issue by Reon90** [EddyVerbruggen/Calendar-PhoneGap-Plugin#269]
`preference name="android-build-tool" value="gradle"
plugin name="cordova-plugin-calendar"

:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:lintVitalRelease
:transformClassesWithDexForRelease
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.95.x86_64/bin/java'' finished with non-zero exit value 2`

**Comment by bau720123** [comment]
hi @Reon90 
are you really sure that your android build fail is "cordova-plugin-calendar" problem
I am using PGB cli-6.0.0 and gradle build and "cordova-plugin-calendar" 4.4.7
but I still build success

please remove your plugins step by step (one by one)
finally you will know what the plugin cause will Android build fail reason

**Comment by Reon90** [comment]
You are rigth, this plugin conflict with another.
