### ISSUE TITLE
Calendar crash on event click

### ISSUE THREAD

**Issue by furyscript** [EddyVerbruggen/Calendar-PhoneGap-Plugin#273]
I add an event with this method with ngCordova:
```
$cordovaCalendar.createEvent({
    title: 'Space Race',
    location: 'The Moon',
    notes: 'Bring sandwiches',
    startDate: new Date(2015, 0, 6, 18, 30, 0, 0, 0),
    endDate: new Date(2015, 1, 6, 12, 0, 0, 0, 0)
  }).then(function (result) {
    // success
  }, function (err) {
    // error
  });
```
When I go to my native calendar on emulator (Api 23, Android 6) and I click on event, my calendar crash.

Do you know why?

**Comment by EddyVerbruggen** [comment]
Should be in the log of the emulator - run `adb logcat`

**Comment by furyscript** [comment]
This @EddyVerbruggen 
```
I/ActivityManager( 1291): Displayed com.android.calendar/.EventInfoActivity: +5s70ms
E/DatabaseUtils( 2035): Writing exception to parcel
E/DatabaseUtils( 2035): java.lang.IllegalArgumentException: the bind value at index 2 is null
E/DatabaseUtils( 2035): 	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
E/DatabaseUtils( 2035): 	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
E/DatabaseUtils( 2035): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
E/DatabaseUtils( 2035): 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
E/DatabaseUtils( 2035): 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
E/DatabaseUtils( 2035): 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:333)
E/DatabaseUtils( 2035): 	at com.android.providers.calendar.CalendarProvider2.query(CalendarProvider2.java:1062)
E/DatabaseUtils( 2035): 	at com.android.providers.calendar.CalendarProvider2.queryInternal(CalendarProvider2.java:1033)
E/DatabaseUtils( 2035): 	at com.android.providers.calendar.CalendarProvider2.query(CalendarProvider2.java:839)
E/DatabaseUtils( 2035): 	at android.content.ContentProvider.query(ContentProvider.java:966)
E/DatabaseUtils( 2035): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
E/DatabaseUtils( 2035): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
E/DatabaseUtils( 2035): 	at android.os.Binder.execTransact(Binder.java:446)
D/AndroidRuntime( 2002): Shutting down VM
--------- beginning of crash
E/AndroidRuntime( 2002): FATAL EXCEPTION: main
E/AndroidRuntime( 2002): Process: com.android.calendar, PID: 2002
E/AndroidRuntime( 2002): java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
E/AndroidRuntime( 2002): 	at com.android.calendar.EventInfoFragment$QueryHandler.onQueryComplete(EventInfoFragment.java:536)
E/AndroidRuntime( 2002): 	at com.android.calendar.AsyncQueryService.handleMessage(AsyncQueryService.java:412)
E/AndroidRuntime( 2002): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2002): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2002): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 2002): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2002): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2002): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 2002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager( 1291):   Force finishing activity 1 com.android.calendar/.EventInfoActivity
W/ActivityManager( 1291):   Force finishing activity 2 com.android.calendar/.AllInOneActivity
```

**Comment by EddyVerbruggen** [comment]
Tried to reproduce but failed on 2 different emulators. Did you see this on a real device as well?

I'd rather see your app crash than the calendar app since that would make debugging this a lot easier.

**Comment by furyscript** [comment]
On my device it works fine @EddyVerbruggen ... Only in the emulator... Maybe because I didn't set google account?? I don't think...

**Comment by JohnRodney** [comment]
@furyscript Everything I have found on google around this error seems to be related to a malformed SQL query which would seem like it was a problem with your emulator interfacing with the client and not likely an issue with this repo.

Source: http://stackoverflow.com/questions/4572090/illegalargumentexception-the-bind-value-at-index-1-is-null

Have you tried updating your emulator, and can you create a series of steps that someone can reproduce this bug?

**Comment by furyscript** [comment]
To reproduce this you can simply add event (like my first comment) in application run / controller @JohnRodney ...

I didn't test with a lot of emulator but with `Google APIs Level 22` and `Google APIs Level 23` not work (When I click in event calendar, the calendar crash).

On my device and tablet it works.
