### ISSUE TITLE
Failed to install 'cordova-plugin-calendar':TypeError: Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by tonholis** [EddyVerbruggen/Calendar-PhoneGap-Plugin#278]
Hi!
I tried to install the plugin but the installation stopped on iOS step:

```
➜  Mobile git:(master) ✗ cordova plugin add cordova-plugin-calendar
Fetching plugin "cordova-plugin-calendar" via npm
Installing "cordova-plugin-calendar" for android
Installing "cordova-plugin-calendar" for ios
Failed to install 'cordova-plugin-calendar':TypeError: Cannot read property 'nodeName' of null
    at Object.parse (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/parse.js:45:26)
    at Object.module.exports.package_name (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:143:22)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:270:67
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:857:14
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:453:9)
Error: Cannot read property 'nodeName' of null
```

I tried to install using repo address but same error.
Any suggestion?

This is my system:

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2 Build version 7C68 


```

**Comment by EddyVerbruggen** [comment]
You're not alone: https://issues.apache.org/jira/browse/CB-8218

And there's more hits on Google. Nothing plugin-specific so can't help you.

**Comment by tonholis** [comment]
OK, thanks Eddy!
