### ISSUE TITLE
Phonegap Build aborts when building with Calendar plugin

### ISSUE THREAD

**Issue by postersw** [EddyVerbruggen/Calendar-PhoneGap-Plugin#291]
I have a small Phonegap app, using only a couple of plugins, that builds fine WITHOUT the Calendar plugin.  But when I add the Calendar plugin, the Phonegap build aborts and will not build.
Here is the config xml statement I am using to pick up the plugin:
    <plugin name="cordova-plugin-calendar" source="npm" />
And I am specifying Gradle:
 <preference name="android-build-tool"         value="gradle"/>   
The plugins I am using are just cordova.device, cordova.inappbrowser, cordova.splashscreen, pubhbots-cordova-plugin (which build fine), and cordova-plugin-calendar (which causes the build to abort).
--------------------------------------------------------------------------------------------
## **SYNOPSIS OF BUILD PROBLEM:**
With the calendar plugin, the phonegap build try to do both a debug and a production (non-debug) build, and aborts with:
FAILURE: Build failed with an exception.
 * What went wrong:
Execution failed for task ':dexRelease'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
                /android-sdk/build-tools/23.0.1/dx --dex --output /project/build/intermediates/dex/release --input-list=/project/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
                2
  Output:             
                UNEXPECTED TOP-LEVEL EXCEPTION:
                com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
                                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
                                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                                at com.android.dx.command.dexer.Main.run(Main.java:277)
                                at com.android.dx.command.dexer.Main.main(Main.java:245)
                                at com.android.dx.command.Main.main(Main.java:106)
----------------------------------------------------------------------------------------------------------------------
## **HERE  IS THE FULL LOG:**
NOTE that  the Calendar plugin somehow causes: CordovaLib: GenerateReleasebuildConfig AND CordovaLib: GenerateDebuildDebugBuildConfig.  This does NOT happen WITHOUT this plugin. So eventually in dexRelease, there is an abort with "Multiple dex files define Landroid/support/annotation/animRes.

Build Date: 2016-05-16 17:39:21 +0000
Build option --'' not recognized (ignoring).
Running: /project/gradlew cdvBuildRelease -b /project/build.gradle -Dorg.gradle.daemon=true -PcdvBuildMultipleApks=false
:preBuild
:compileReleaseNdk
:preReleaseBuild
:checkReleaseManifest
:preDebugBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
 
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
 
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV42400Alpha1Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
 
:preDexRelease
:dexRelease
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                at com.android.dx.command.dexer.Main.run(Main.java:277)
                at com.android.dx.command.dexer.Main.main(Main.java:245)
                at com.android.dx.command.Main.main(Main.java:106)
 
FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':dexRelease'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
                /android-sdk/build-tools/23.0.1/dx --dex --output /project/build/intermediates/dex/release --input-list=/project/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
                2
  Output:
               
                UNEXPECTED TOP-LEVEL EXCEPTION:
                com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
                                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
                                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                                at com.android.dx.command.dexer.Main.run(Main.java:277)
                                at com.android.dx.command.dexer.Main.main(Main.java:245)
                                at com.android.dx.command.Main.main(Main.java:106)
               
 
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
BUILD FAILED
 
Total time: 28.092 secs
 
/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true,-PcdvBuildMultipleApks=false

**Comment by EddyVerbruggen** [comment]
I just dropped the support library from this plugin, which seems to have caused this issue. Please test version 4.5.0. Not yet on npm, but you can link to this repo from PGB these days.

**Comment by postersw** [comment]
Thank you.  This fixed the problem of the Phonegap Build about with building the Android version with the plugin. (And BTW the plugin is great!).

 

Bob
