### ISSUE TITLE
Failed to install 'cordova-plugin-calendar':Error: Uh oh!

### ISSUE THREAD

**Issue by sudheerrepala** [EddyVerbruggen/Calendar-PhoneGap-Plugin#325]
Hi,

The plugin was working until recently, however now we are getting the below error[Phonegap build, version :cli-6.3.0:]

Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-calendar':Error: Uh oh!
ENOENT: no such file or directory, open '/private/project/cordova/plugins/cordova-plugin-calendar/test/tests.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at handlers.js-module.install (/private/project/cordova/lib/plugman/pluginHandlers.js:161:36)
    at Object.ActionStack.process (/private/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/private/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/private/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/private/project/cordova/Api.js:219:10)
    at handleInstall (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:580:6)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:384:20
Uh oh!
ENOENT: no such file or directory, open '/private/project/cordova/plugins/cordova-plugin-calendar/test/tests.js'

**Comment by EddyVerbruggen** [comment]
I'm afraid the `.npmignore` file was a bit too aggressive. Please retry (4.5.3).
