### ISSUE TITLE
Android S Planner stops working on event click in custom calendar

### ISSUE THREAD

**Issue by cbopp** [EddyVerbruggen/Calendar-PhoneGap-Plugin#353]
Hey,
the default calendar app on my Samsung S5 is S Planner from Samsung.

**Default calendar => OK**
If I create an event within the default calendar (MyEvents in S Planner { calendarName:'MyEvents', calendarId:1) everything is fine. I can go into the calendar app and open the newly created event.

**Custom calendar => FAILURE**
If I create a custom calendar prior to creating an event and thus create an event within the new or already existing custom calendar, S Planner crashes while trying to open the new event within the calendar app.

In both cases the calendar is available in its chosen color and the event is shown as an colored time slot. Just trying to view the event details with a click on its' time slot crashed the calendar app.

**Approaches**
I've tried creating events with various constellations, with or without location, notes, url, 1st & 2nd reminder and so on to no avail. Only the chosen calendar triggers the failure (default or custom). Since there are only two parameters to provide while creating an calendar, I couldn't do more tests (name, color).

**Logcat**
```
12-16 12:17:10.291  3551  3551 D GameManagerService: NotifyRunnable. pkg: com.android.calendar, type: 4, isMinimized: false, isTunableApp: false
12-16 12:17:10.301 30009 30009 D AndroidRuntime: Shutting down VM
12-16 12:17:10.301 30009 30009 E AndroidRuntime: FATAL EXCEPTION: main
12-16 12:17:10.301 30009 30009 E AndroidRuntime: Process: com.android.calendar, PID: 30009
12-16 12:17:10.301 30009 30009 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at com.android.calendar.be.b(Event.java:898)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at com.android.calendar.timeline.g.a(DayView.java:3432)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at com.android.calendar.timeline.g.b(DayView.java:3414)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at com.android.calendar.timeline.g.a(DayView.java:2464)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at com.android.calendar.timeline.g.e(DayView.java:2720)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at com.android.calendar.timeline.g.onDraw(DayView.java:2213)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.draw(View.java:17476)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16469)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:16429)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3184)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2983)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2572)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7450)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:695)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:631)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
12-16 12:17:10.301 30009 30009 E AndroidRuntime:        at android.os.Handler.handleCallback
```

**Conclusion**
I guess that S Planner is trying to deviate some default settings from a custom calendar (apart from calendar name and color) and is thus running into a NullPointerException while doing so...

**Comment by cbopp** [comment]
Solution:

Adding the following parameter within calendar creation fixes this issue. This parameter is also stated as mandatory in the [docs](https://developer.android.com/reference/android/provider/CalendarContract.Calendars.html).

nl.xservices.plugins.accessor.AbstractCalendarAccessor::createCalendar
+ cv.put(CalendarContract.Calendars.OWNER_ACCOUNT, "AccountName");
