### ISSUE TITLE
App crashed on Android 6.0 due to a calendar issue

### ISSUE THREAD

**Issue by int9solutions** [EddyVerbruggen/Calendar-PhoneGap-Plugin#375]
Hi,

Our mobile application uses the telerik verified 4.5.5 plugin. It works fine on iOS and Android 5*. But the app crashed on Android 6*. Our research indicates that the permissioning for calendar access has changed in 6.0. Please find the crash log below,

********

02-17 06:41:12.209 2238-4841/? W/ActivityManager: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{80e2c24 25228:org.peaceforward.surfaceapp/u0a214} (pid=25228, uid=10214) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
02-17 06:41:12.217 25228-25288/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
                                                   Process: org.peaceforward.surfaceapp, PID: 25228
                                                   java.lang.SecurityException: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{80e2c24 25228:org.peaceforward.surfaceapp/u0a214} (pid=25228, uid=10214) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
                                                       at android.os.Parcel.readException(Parcel.java:1599)
                                                       at android.os.Parcel.readException(Parcel.java:1552)
                                                       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3652)
                                                       at android.app.ActivityThread.acquireProvider(ActivityThread.java:4892)
                                                       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2020)
                                                       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1491)
                                                       at android.content.ContentResolver.query(ContentResolver.java:484)
                                                       at android.content.ContentResolver.query(ContentResolver.java:442)
                                                       at nl.xservices.plugins.accessor.CalendarProviderAccessor.queryEventInstances(CalendarProviderAccessor.java:79)
                                                       at nl.xservices.plugins.accessor.AbstractCalendarAccessor.fetchEventInstances(AbstractCalendarAccessor.java:194)
                                                       at nl.xservices.plugins.accessor.AbstractCalendarAccessor.findEvents(AbstractCalendarAccessor.java:382)
                                                       at nl.xservices.plugins.Calendar$8.run(Calendar.java:482)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
02-17 06:41:12.222 2238-2278/? W/ActivityManager:   Force finishing activity org.peaceforward.surfaceapp/.TelerikCallbackActivity
02-17 06:41:12.318 2238-4152/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I49f5588d88)
                                             OpenGL ES Shader Compiler Version: E031.29.00.00
                                             Build Date: 12/19/15 Sat
                                             Local Branch: mybranch17333385
                                             Remote Branch: quic/LA.BF.1.1.3_rb1.6
                                             Local Patches: NONE
                                             Reconstruct Branch: NOTHING
02-17 06:41:12.318 2238-4152/? I/OpenGLRenderer: Initialized EGL, version 1.4
02-17 06:41:12.352 2238-4864/? I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
02-17 06:41:12.355 4973-4973/? I/[LGHome]EVENT: onStart

********

Please let us know if you need anything else,

**Comment by EddyVerbruggen** [comment]
That's very strange as [this]https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/6b098d8622b4088758a0e235613258fdffc79278/src/android/nl/xservices/plugins/Calendar.java#L470-L473) guards the method you invoke with a permission check. Did you ever get the popup to request the permission?

Could be the permissions are missing in the generated platforms/android/somewhere/AndroidManifest.xml.. but the plugin is supposed to add them.

As a workaround you could target an Android SDK lower than 23.

**Comment by int9solutions** [comment]
Thanks for the quick response.
Below is a snip from our AndroidManifest.xml

----
<manifest android:versionCode="$AndroidVersionCode$"
          android:versionName="$BundleVersion$"
          package="org.peaceforward.surfaceapp"
          android:windowSoftInputMode="adjustPan"
          android:hardwareAccelerated="true"
          xmlns:android="http://schemas.android.com/apk/res/android" >
    <supports-screens
        android:largeScreens="true"
        android:normalScreens="true"
        android:smallScreens="true"
        android:xlargeScreens="true"
        android:resizeable="true"
        android:anyDensity="true"
        />
    <uses-permission android:name="android.permission.INTERNET" />
   <uses-permission android:name="android.permission.WRITE_CALENDAR" />
   <uses-permission android:name="android.permission.READ_CALENDAR" />
   <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <application android:label="@string/app_name"
                 android:icon="@drawable/icon"
                 android:hardwareAccelerated="$AndroidHardwareAcceleration$">

Could you please confirmt that the version in telerik(4.5.5) has the latest code? I will try the target SDK= 22 and report it here.

**Comment by int9solutions** [comment]
<addr> <manifest android:versionCode="$AndroidVersionCode$"
          android:versionName="$BundleVersion$"
          package="org.peaceforward.surfaceapp"
          android:windowSoftInputMode="adjustPan"
          android:hardwareAccelerated="true"
          xmlns:android="http://schemas.android.com/apk/res/android" >
    <supports-screens
        android:largeScreens="true"
        android:normalScreens="true"
        android:smallScreens="true"
        android:xlargeScreens="true"
        android:resizeable="true"
        android:anyDensity="true"
        />
    <uses-permission android:name="android.permission.INTERNET" />
   <uses-permission android:name="android.permission.WRITE_CALENDAR" />
   <uses-permission android:name="android.permission.READ_CALENDAR" />
   <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <application android:label="@string/app_name"
                 android:icon="@drawable/icon"
                 android:hardwareAccelerated="$AndroidHardwareAcceleration$">

**Comment by int9solutions** [comment]
Tried to paste the XML version of androidmanifest but it just keeps showing as blank :-)

BTW, our initial tests with targetSD=22 seems to be working. We will be performing additional testing to confirm

**Comment by EddyVerbruggen** [comment]
The version at Telerik is identical to the latest release of this repo. Btw, to add code to a comment enclose it in backticks: `, use three for multi-line code: ```

**Comment by int9solutions** [comment]
Here we go,
```<manifest android:versionCode="$AndroidVersionCode$"
          android:versionName="$BundleVersion$"
          package="org.peaceforward.surfaceapp"
          android:windowSoftInputMode="adjustPan"
          android:hardwareAccelerated="true"
          xmlns:android="http://schemas.android.com/apk/res/android" >
    <supports-screens
        android:largeScreens="true"
        android:normalScreens="true"
        android:smallScreens="true"
        android:xlargeScreens="true"
        android:resizeable="true"
        android:anyDensity="true"
        />
    <uses-permission android:name="android.permission.INTERNET" />
   <uses-permission android:name="android.permission.WRITE_CALENDAR" />
   <uses-permission android:name="android.permission.READ_CALENDAR" />
   <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <application android:label="@string/app_name"
                 android:icon="@drawable/icon"
                 android:hardwareAccelerated="$AndroidHardwareAcceleration$">
```

**Comment by int9solutions** [comment]
Hi Ed,

We tested the APK with target SDK 22. It works as a standalone function but when we tried to deploy this to Appstore, we are not able to complete the operation because the previous version is on 23. The appstore bailed out saying,

_"It is forbidden to downgrade devices which previously used M permissions (target SDK 23 and above) to APKs which use old style permissions (target SDK 22 and below). This occurs in the change from version 282 (target SDK 23) to version 292 (target SDK 22)."_

Any thoughts on how we can make the APK work with 23 ?

**Comment by int9solutions** [comment]
After further debugging, it is our assumption that this method in Calendar.java always returns 'true' on Android 6.0+. 

calendarPermissionGranted(types)

Can you check? 

How did we conclude?
We tried to call the 'hasReadWritePermission' and it always returns true on Android 6.0. Not sure why 6.0 does this but it could be because of the runtime permissions.

Any thoughts? We are at a crunch to release this functionality this weekend,

**Comment by EddyVerbruggen** [comment]
Please link to the code fragments so we're all on the same page. You mean [this](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/6b098d8622b4088758a0e235613258fdffc79278/src/android/nl/xservices/plugins/Calendar.java#L163-L173) code always returns `true`? That only correct if you're running SDK levels before 22. When building for 23+ and running Android 6+ that method should trigger the auth prompt.

If you're in a hurry and want me to look at your code then email me privately please.

**Comment by int9solutions** [comment]
Hi Ed,The method that is used to call the calendar API is as below,setupCalEvents: function(eventsToCreate) { var createSingleEvent = function (events, i) { var start; var end; //var calendarOptions = window.plugins.calendar.getCalendarOptions(); var calendarOptions = app.getCalendarOptions(); function onFindSuccess(argument) {  if(argument == "") window.plugins.calendar.createEventWithOptions("Title", "Video delivery on mobile", "app.com", start, end, calendarOptions, onSuccess, onError); else { //alert("find success " + argument); createSingleEvent(events, i+1);  } } function onFindError (argument) { myApp.alert("Error while locating a previous calendar entry. Submit a question using the 'Contact us' form. "+argument); }function onSuccess (argument) { //alert("created event. moving to next event"); createSingleEvent(events, i+1);  }function onError (argument) { myApp.alert("Error while creating a calendar entry. Submit a question using the 'Contact us' form. "+argument); }function onDeleteSuccess(argument) { //alert("delete success");  } function onDeleteError(argument) { myApp.alert("Discarding previous calendar events failed. Please notify us through the contact us form"); } if (i < events.length)  { //alert("creating event->"+i); start=new Date(events[i].practice_day.replace(/-/g, '/')); start.setMinutes(events[i].startTime.substr(-2)); start.setSeconds(0);  start.setHours(("0" + events[i].startTime.slice(0,-2)).slice(-2)); //alert("Start Day -> "+start);  //var end=new Date(practiceDay.replace(/-/g, '/')); end=new Date(events[i].practice_day.replace(/-/g, '/')); end.setMinutes(events[i].endTime.substr(-2)); end.setSeconds(0); end.setHours(("0" + events[i].endTime.slice(0,-2)).slice(-2)); //alert("End day -> "+end);window.plugins.calendar.findEventWithOptions("Title", "Video delivery on mobile", "app.com", start, end, calendarOptions, onFindSuccess, onFindError); }  //placeholder reminder for tomorrow else if(i == events.length) {start=new Date(); start.setDate(start.getDate()+1); start.setMinutes(0); start.setSeconds(0);  start.setHours("06");end=new Date(); end.setDate(end.getDate()+1); end.setMinutes("10"); end.setSeconds(0);  end.setHours("06");  window.plugins.calendar.findEventWithOptions("Title", "Video delivery on mobile", "app.com", start, end, calendarOptions, onFindSuccess, onFindError);} //placeholder reminder for day after tomorrow else if(i == (events.length + 1)) {start=new Date(); start.setDate(start.getDate()+2); start.setMinutes(0); start.setSeconds(0);  start.setHours("06");end=new Date(); end.setDate(end.getDate()+2); end.setMinutes("10"); end.setSeconds(0);  end.setHours("06");  window.plugins.calendar.findEventWithOptions("Title", "Video delivery on mobile", "app.com", start, end, calendarOptions, onFindSuccess, onFindError);} else if(i == (events.length + 2)) { start=new Date(); start.setDate(start.getDate()-1); start.setMinutes(0); start.setSeconds(0);  start.setHours("05");end=new Date(); end.setDate(end.getDate()-1); end.setMinutes("00"); end.setSeconds(0);  end.setHours("23");  //alert("deleting events->"+i);  window.plugins.calendar.deleteEvent("Title", "Video delivery on mobile", "app.com",start, end, onDeleteSuccess, onDeleteError); }}; createSingleEvent(eventsToCreate, 0); },It works fine on iPhone, Android <6.0. On Android 6.0, it neither does popup the permission request window nor allow the app the continue. It just crashes the app,We will really appreciate if you can help this weekend,On February 18, 2017 at 3:18 AM Eddy Verbruggen <notifications@github.com> wrote:Please link to the code fragments so we're all on the same page. You mean this code always returns true? That only correct if you're running SDK levels before 22. When building for 23+ and running Android 6+ that method should trigger the auth prompt.If you're in a hurry and want me to look at your code then email me privately please.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by int9solutions** [comment]
Thanks. We have just emailed you the code that calls the calendar events. It just does not work on Android 6.0+. will appreciate if you could look into this today,

**Comment by michelebravo** [comment]
Hi!
I have the same problem with my app. Could you post the bugfix please?

**Comment by vousys** [comment]
I'm having the same issue
