### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by int21ve** [EddyVerbruggen/Calendar-PhoneGap-Plugin#394]
Device: Android 4.2.2 (real device)
Environment: Cordova/Angular1

I was trying to use this function
```
            $cordovaCalendar.createCalendar({
                calendarName: "The Name",
                calendarColor: '#FF0000'
            });
```

Output from debug

```
getProviderByName: com.android.calendar , callingUid = 10067
 Creating calendar failed.
java.lang.NullPointerException
 	at nl.xservices.plugins.accessor.AbstractCalendarAccessor.createCalendar(AbstractCalendarAccessor.java:499)
 	at nl.xservices.plugins.Calendar$4.run(Calendar.java:300)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:838)
```

**Comment by BaR488** [comment]
Hi, i have the same problem.
I think, on your device exist calendar without name. 
When you try to create calendar, plugin is check that calendar exist with that name.

[https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/4.5.5/src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java#L499](url)

Problem here:
```
Cursor result = contentResolver.query(evuri, new String[] {CalendarContract.Calendars._ID, CalendarContract.Calendars.NAME, CalendarContract.Calendars.CALENDAR_DISPLAY_NAME}, null, null, null);
if (result != null) {
  while (result.moveToNext()) {
    if (result.getString(1).equals(calendarName) || result.getString(2).equals(calendarName)) {
  	result.close();
  	return null;
    }
  }
  result.close();
}
```

Need change to:
```
Cursor result = contentResolver.query(evuri, new String[] {CalendarContract.Calendars._ID, CalendarContract.Calendars.NAME, CalendarContract.Calendars.CALENDAR_DISPLAY_NAME}, null, null, null);
if (result != null) {
  while (result.moveToNext()) {
    if ((result.getString(1) != null && result.getString(1).equals(calendarName)) || (result.getString(2) != null && result.getString(2).equals(calendarName))) {
  	result.close();
  	return null;
    }
  }
result.close();
}
```
