### ISSUE TITLE
Android crashing (no permissions added to app)

### ISSUE THREAD

**Issue by juanjoseadan** [EddyVerbruggen/Calendar-PhoneGap-Plugin#471]
I recently implemented this plugin in my Ionic 3+ app and, at this moment, I've found many issues.

This time I want to report the next bug:
On Android devices running API 19 and API 22 the app crashes inmediately after using any function.

If I go to Settings > Apps > MyAwesomeAppName I can't see Permissions for Read/Write to Calendar.

Exploring deeply into the Android project I see the permissions added into AndroidManifest.xml

This is the error I get in Logcat:

`
05-17 18:24:18.647 5412-5468/com.myawesomeapp.name D/Calendar: Initializing calendar plugin
05-17 18:24:18.650 5412-5468/com.myawesomeapp.name E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 4 rows, 4 columns.
    
    --------- beginning of crash
05-17 18:24:18.651 5412-5468/com.myawesomeapp.name E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
    Process: com.myawesomeapp.name, PID: 5412
    java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:438)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
        at android.database.CursorWrapper.getString(CursorWrapper.java:114)
        at nl.xservices.plugins.accessor.AbstractCalendarAccessor.getActiveCalendars(AbstractCalendarAccessor.java:291)
        at nl.xservices.plugins.Calendar$3.run(Calendar.java:270)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    
    
    --------- beginning of system
05-17 18:24:18.651 1497-2613/system_process W/ActivityManager:   Force finishing activity 1 com.myawesomeapp.name/.MainActivity
`

Is there something I could be missing?

**Comment by EddyVerbruggen** [comment]
Could be a PR that was part of 5.1.0 broke something. Can you try 5.0.0?
