### ISSUE TITLE
Android listCallendars crashes app

### ISSUE THREAD

**Issue by Medtrack** [EddyVerbruggen/Calendar-PhoneGap-Plugin#473]
Hello, running some tests on AWS Device Farm I have found that this plugin crashes when we call _listCalendars_.

The "_isPrimary_" key is not present on some devices, I have found Samsung Galaxy Note 2, 3 and 4 on _Amazon Web Services Device Farm_ with Android 4.4 and 5.

The code crashes because of a cursor with the wrong index in the method _getActiveCalendars_ on _AbstractCalendarAccessor.java_. It looks that the "_isPrimary_" key is not present on all devices.
https://stackoverflow.com/questions/25870556/check-if-calendar-is-primary

The call _cursor.getColumnIndex(this.getKey(KeyIndex.IS_PRIMARY))_ returns _-1_. After that, the cursor looking for a -1 index crashes the app.

```
calendar.put("isPrimary", "1".equals(cursor.getString(cursor.getColumnIndex(this.getKey(KeyIndex.IS_PRIMARY)))));
```

The docs say that it has to do to the owner... I don't really know what they mean:
https://developer.android.com/reference/android/provider/CalendarContract.CalendarColumns

```
public final JSONArray getActiveCalendars() throws JSONException {
    Cursor cursor = queryCalendars(
            new String[]{
                    this.getKey(KeyIndex.CALENDARS_ID),
                    this.getKey(KeyIndex.CALENDARS_NAME),
                    this.getKey(KeyIndex.CALENDARS_DISPLAY_NAME),
                    this.getKey(KeyIndex.IS_PRIMARY)
            },
            this.getKey(KeyIndex.CALENDARS_VISIBLE) + "=1", null, null
    );
    if (cursor == null) {
        return null;
    }
    JSONArray calendarsWrapper = new JSONArray();
    if (cursor.moveToFirst()) {
        do {
            JSONObject calendar = new JSONObject();
            calendar.put("id", cursor.getString(cursor.getColumnIndex(this.getKey(KeyIndex.CALENDARS_ID))));
            calendar.put("name", cursor.getString(cursor.getColumnIndex(this.getKey(KeyIndex.CALENDARS_NAME))));
            calendar.put("displayname", cursor.getString(cursor.getColumnIndex(this.getKey(KeyIndex.CALENDARS_DISPLAY_NAME))));
            calendar.put("isPrimary", "1".equals(cursor.getString(cursor.getColumnIndex(this.getKey(KeyIndex.IS_PRIMARY)))));
            calendarsWrapper.put(calendar);
        } while (cursor.moveToNext());
        cursor.close();
    }
    return calendarsWrapper;
}
```

Here is the log from the crash.

```
06-07 11:15:56.236 12285 12471 E CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 4 columns.
06-07 11:15:56.236 12285 12471 W dalvikvm: threadid=23: thread exiting with uncaught exception (group=0x41e61c08)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
06-07 11:15:56.241 12285 12471 E AndroidRuntime: Process: me.tararea.calendar, PID: 12285
06-07 11:15:56.241 12285 12471 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at android.database.CursorWindow.nativeGetString(Native Method)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at android.database.CursorWindow.getString(CursorWindow.java:439)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at android.database.CursorWrapper.getString(CursorWrapper.java:114)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at nl.xservices.plugins.accessor.AbstractCalendarAccessor.getActiveCalendars(AbstractCalendarAccessor.java:291)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at nl.xservices.plugins.Calendar$3.run(Calendar.java:270)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 11:15:56.241 12285 12471 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
```

A quick way to test:

- create a cordova app that calls listCalendar
- create a free, 1000 minutes account on AWS Device Farm
- test the app on Samsung Galaxy Note 2.

Thank you very much for your work.

**Comment by EddyVerbruggen** [comment]
Ah, interesting find. Would you be willing to attempt doing a pull request to fix it?

**Comment by Medtrack** [comment]
@EddyVerbruggen I am already on it. :-)

Thank you.

**Comment by EddyVerbruggen** [comment]
Fixed by your great PR!
